Repository MIT-Emerging-Talent/ET6-foundations-group-27, pull requests merged in 2025-01, with the labels that each got.

#57 Armstrong number
  solutions/armstrong_checker.py
  solutions/tests/test_armstrong_checker.py
Labels: enhancement

#34 Harmonic sequence
  solutions/harmonic_sequence.py
  solutions/tests/test_harmonic_sequence.py
Labels: writing

#65 factorial challenges
  solutions/factorial.py
  solutions/tests/test_factorial.py
Labels: good first issue

#64 Stars triangle draw
  .vscode/settings.json
  solutions/draw_triangle.py
  solutions/tests/test_draw_triangle.py
Labels: good first issue

#35 Comminocation file
  .vscode/settings.json
  collaboration/communication.md
Labels: documentation, writing

#67 summation challenges
  solutions/summation.py
  solutions/tests/test_summation.py
Labels: good first issue

#79 Retrospective
  collaboration/retrospective.md
Labels: documentation

#82 Enhancement - Armstrong Checker
  solutions/armstrong_checker.py
  solutions/tests/test_armstrong_checker.py
Labels: enhancement

#84 Enhancement - Fuel Gauge
  solutions/fuel_gauge.py
  solutions/tests/test_fuel_gauge.py
Labels: enhancement

#85 Modules headers and fixing ruff for word count and copy file to file problems
  solutions/copy_from_file_to_file.py
  solutions/tests/test_copy_from_file_to_file.py
  solutions/tests/test_word_count_from_file.py
  solutions/word_count_from_file.py
Labels: enhancement

#86 enhansments
  solutions/harmonic_sequence.py
  solutions/tests/test_harmonic_sequence.py
Labels: enhancement

#90 enhancment
  solutions/FooBar_code.py
  solutions/tests/test_FooBar_code.py
Labels: enhancement

#91 adding enhancment
  solutions/count_characters.py
  solutions/tests/test_count_characters.py
Labels: enhancement
